# Sourced by the source and release installers. Requires Bash 3.2 or newer.

fwm_update_shell_rc() {
    local requested=$1 loader=$2 shell=$3 target link depth=0 parent temporary backup
    local begin='# >>> fwm shell completion >>>'
    local end='# <<< fwm shell completion <<<'
    target=$requested
    # Preserve dotfile-manager symlinks by replacing their target atomically.
    while [[ -L $target ]]; do
        (( depth < 40 )) || { printf 'error: too many shell startup symlinks: %s\n' "$requested" >&2; return 1; }
        link=$(readlink "$target") || return 1
        case "$link" in
            /*) target=$link ;;
            *) target=$(dirname -- "$target")/$link ;;
        esac
        depth=$((depth + 1))
    done
    if [[ -e $target && ! -f $target ]]; then
        printf 'error: shell startup path is not a regular file: %s\n' "$requested" >&2
        return 1
    fi
    parent=$(dirname -- "$target")
    mkdir -p -- "$parent"
    temporary=$(mktemp "$parent/.fwm-shell-rc.XXXXXX")
    if [[ -f $target ]]; then
        cp -p -- "$target" "$temporary"
        # Refuse malformed markers rather than discard the rest of the file.
        if ! awk -v begin="$begin" -v end="$end" '
            $0 == begin { if (inside) exit 1; inside = 1; next }
            $0 == end { if (!inside) exit 1; inside = 0; next }
            !inside { print }
            END { if (inside) exit 1 }
        ' "$target" > "$temporary"; then
            rm -f -- "$temporary"
            printf 'error: incomplete fwm completion block in %s; startup file was preserved\n' "$requested" >&2
            return 1
        fi
    fi
    {
        printf '%s\n' "$begin"
        if [[ $shell == bash ]]; then
            printf 'if [ -n "${BASH_VERSION-}" ] && [ -r %q ]; then\n' "$loader"
        else
            printf 'if [ -n "${ZSH_VERSION-}" ] && [ -r %q ]; then\n' "$loader"
        fi
        printf '    . %q\n' "$loader"
        printf 'fi\n%s\n' "$end"
    } >> "$temporary"
    if [[ -f $target ]] && cmp -s -- "$target" "$temporary"; then
        rm -f -- "$temporary"
        printf 'Completion startup already configured: %s\n' "$requested"
        return 0
    fi
    if [[ -f $target ]]; then
        backup=$(mktemp "$target.fwm-backup.XXXXXX")
        cp -p -- "$target" "$backup"
        printf 'Startup backup: %s\n' "$backup"
    fi
    mv -f -- "$temporary" "$target"
    printf 'Configured completion startup: %s\n' "$requested"
}

install_shell_completions() {
    local root=$1 shell=$2 rc=$3 temporary candidate profile loader
    mkdir -p -- "$root/share"
    temporary=$(mktemp -d "$root/share/.fwm-completions.XXXXXX")
    if ! "$root/bin/fwm" completions zsh > "$temporary/_fwm" ||
       ! "$root/bin/fwm" completions bash > "$temporary/fwm"; then
        rm -rf -- "$temporary"
        printf 'error: could not generate completion scripts from the installed fwm\n' >&2
        return 1
    fi
    for candidate in bash zsh; do
        loader="$temporary/shell-init.$candidate"
        {
            printf '# Generated by fwm installer.\n'
            printf '_fwm_install_bin=%q\n' "$root/bin"
            cat <<'EOF'
# Prefer this installation over older fwm binaries and avoid duplicate entries.
_fwm_install_rest=$PATH
_fwm_install_tail=
while :; do
    case "$_fwm_install_rest" in
        *:*)
            _fwm_install_entry=${_fwm_install_rest%%:*}
            _fwm_install_rest=${_fwm_install_rest#*:}
            _fwm_install_more=yes
            ;;
        *)
            _fwm_install_entry=$_fwm_install_rest
            _fwm_install_more=no
            ;;
    esac
    if [ "$_fwm_install_entry" != "$_fwm_install_bin" ]; then
        _fwm_install_tail=$_fwm_install_tail:$_fwm_install_entry
    fi
    [ "$_fwm_install_more" = yes ] || break
done
export PATH="$_fwm_install_bin$_fwm_install_tail"
unset _fwm_install_bin _fwm_install_rest _fwm_install_tail _fwm_install_entry _fwm_install_more
EOF
            if [[ $candidate == zsh ]]; then
                cat <<'EOF'
if (( ! $+functions[compdef] )); then
    autoload -Uz compinit
    compinit
fi
EOF
                printf 'source <(%q completions zsh)\n' "$root/bin/fwm"
            else
                # Evaluate registration code from our executable, never values
                # supplied as completion candidates or command-line input.
                printf 'eval "$(%q completions bash)"\n' "$root/bin/fwm"
            fi
        } > "$loader"
    done
    chmod 644 "$temporary"/*
    mkdir -p -- "$root/share/zsh/site-functions" "$root/share/bash-completion/completions" "$root/share/fwm"
    mv -f -- "$temporary/_fwm" "$root/share/zsh/site-functions/_fwm"
    mv -f -- "$temporary/fwm" "$root/share/bash-completion/completions/fwm"
    mv -f -- "$temporary/shell-init.zsh" "$root/share/fwm/shell-init.zsh"
    mv -f -- "$temporary/shell-init.bash" "$root/share/fwm/shell-init.bash"
    rmdir -- "$temporary"
    printf 'Installed Bash and Zsh completion scripts under %s/share\n' "$root"

    if [[ $shell == none ]]; then
        printf 'Startup files unchanged (--shell none). To enable completion, source:\n'
        printf '  Zsh:  source %q\n' "$root/share/fwm/shell-init.zsh"
        printf '  Bash: source %q\n' "$root/share/fwm/shell-init.bash"
        return 0
    fi
    loader="$root/share/fwm/shell-init.$shell"
    if [[ -n $rc ]]; then
        fwm_update_shell_rc "$rc" "$loader" "$shell"
    elif [[ $shell == zsh ]]; then
        fwm_update_shell_rc "${ZDOTDIR:-$HOME}/.zshrc" "$loader" "$shell"
    else
        fwm_update_shell_rc "$HOME/.bashrc" "$loader" "$shell"
        # Login Bash reads only the first existing profile, while non-login
        # interactive Bash reads .bashrc. Cover both without sourcing user code.
        profile=$HOME/.bash_profile
        for candidate in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
            if [[ -f $candidate ]]; then profile=$candidate; break; fi
        done
        fwm_update_shell_rc "$profile" "$loader" "$shell"
    fi
    printf 'Completion is ready in new terminals. Activate in this terminal with:\n'
    printf '  source %q\n' "$loader"
}
